### ISSUE TITLE
comparing specific font glyph accross fonts

### ISSUE THREAD

**Issue by maliky** [FontManager/font-manager#100]
Hi, 
I'm looking hard to find a way to compare a specific glyph say 'C' accross different fonts.
It would be great if the compare menu had the option to add several font at once (ie. Ctrl+A + +) while also specifying the text to be compared.

Thank you

**Comment by JerryCasiano** [comment]
> I'm looking hard to find a way to compare a specific glyph say 'C' accross different fonts.

Is there some reason the custom text entry provided in the compare view between the controls doesn't work for this purpose?

>  It would be great if the compare menu had the option to add several font at once (ie. Ctrl+A + +) while also specifying the text to be compared.

The compare view is not really intended for adding so many fonts that this becomes an issue, at least in my opinion/usage. So I probably will not add such a shortcut. If someone were to provide a patch that does so I'd be happy to review/merge.

Until then I suggest you make a collection and use the browse view, since that also provides a custom text entry, for comparison of many fonts at once.

**Comment by JerryCasiano** [comment]
Closing due to lack of response.

**Comment by JerryCasiano** [comment]
> Secondly, I did find, but could not find it in the compare view again, a way to limit the personalize the text to compare.

Sounds like you're using an outdated version.

Are you using the latest release?
