### ISSUE TITLE
Invalid Pointer

### ISSUE THREAD

**Issue by ahloiscreamo** [FontManager/font-manager#108]
Hi,
the application failed to run when i launch it.

Version
fontmanager-0.7.7_1 

System
 `Linux void_ahloi 5.4.10_2 #1 SMP PREEMPT Fri Jan 10 12:11:53 UTC 2020 x86_64 GNU/Linux`

Terminal output
```
ahloi@void_ahloi:~
➤ font-manager
[font-manager]-Message: 00:13:21.848: ArchiveManager.vala:59: Install file-roller to enable archive support
free(): invalid pointer
fish: “font-manager” terminated by signal SIGABRT (Abort)
ahloi@void_ahloi:~
```

**Comment by JerryCasiano** [comment]
In order to even try to reproduce this, at a minimum, I need to know exactly what version of Void you are running, i.e. a link to the ISO you used for installation, any significant changes you may have made and what method you used to install the application.

You can also assist by running the application using gdb and posting a trace.

**Comment by JerryCasiano** [comment]
Feel free to re-open if/when you are able to provide more information and help troubleshoot your issue.
