### ISSUE TITLE
Emoji flag sequences

### ISSUE THREAD

**Issue by RocketMan** [FontManager/font-manager#109]
Some fonts (for example, Noto Color Emoji) include glyphs for country flags.  Rather than allocating a single code point for each flag, these glyphs are accessed via a two-character [Regional Indicator Symbol](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol) sequence.  These are known as 'emoji flag sequences'.

For example, the Australian flag is specified by two RIS code points:🇦(U+1F1E6) followed by 🇺 (U+1F1FA).  When these two code points run together, it looks like this: 🇦🇺

The Font Manager shows the glyphs for the constituent RIS's, but does not display the emoji flag sequence glyphs formed by combinations of RIS's.  Although the glyph for the Australian flag (for example) is in the Noto Color Emoji font, Font Manager does not show it, as far as I can tell.

Thanks for considering the issue.  Also, thank you for creating this application; it is not only useful, but visually attractive as well.

**Comment by JerryCasiano** [comment]
So...

On the one hand I would like to support this, if the font actually has a glyph for this I feel that it *should* be present in the character map.

On the other hand the way this is implemented is very unfortunate, it's almost like an easter egg, and that makes this hard to support properly in our context.. 

For starters, supporting this in the character map would probably require quite a few changes, for limited benefit, but more importantly it would also mean adding *special cases* for those fonts which actually support this because as far as I can tell just because a font file contains those codepoints does *not* mean that they will be rendered as an emoji flag when used together, they may be rendered simply as letters next to each other, tofu, a blank or anything at all really.

I'm going to leave this open for now because I'm still leaning towards supporting it and I would like to get back to this when I have more time to do some research and actually look at what the changes needed will be. May be a while though.

Thanks.

**Comment by JerryCasiano** [comment]
So for anyone still interested in this feature it's implemented in master.

I'm going to leave this open for a while in case any issues related to the changes pop up.

As far the implementation goes it's very basic and simply tacks on all the valid country codes, all 270 of them, onto to the end of the character map IF all 26 regional indicator symbols are present in the font.

There is no attempt to verify that any of those glyphs actually exist 

This portion of the character map is also not taken into account when using the search feature.

And there is no filtering for this case so in order to view these you will need to scroll down to the end of the character map.

**Comment by PF4Public** [comment]
Works fine:
![image](https://user-images.githubusercontent.com/10319700/130282961-fdfe0aff-6345-4af6-847f-1da6daa65a14.png)

@JerryCasiano Why didn't you create a group on the left for them? Is it too complicated?

**Comment by JerryCasiano** [comment]
@PF4Public 

> Why didn't you create a group filter on the left for them? Is it too complicated?

Sort of.

I mean, aside from this particular case every other entry in the character map consists of a single codepoint so our filters are just arrays/lists of integers, when you select a filter it just filters out any codepoints that aren't in the array which is nice and simple.  To support this we would likely need a more complicated structure rather than just a simple list or array.

Reworking our filter interface to fit the case where a character is composed of multiple codepoints, which doesn't appear to be very common at all, would definitely complicate things a little and doesn't seem worthwhile just yet. 

BUT I haven't ruled out providing a filter, I too think it would be nicer that way. Might use some workaround involving special processing for a list only containing regional indicator symbols. That seems like the path of least resistance...

I'll try it in a bit and see how it goes.

**Comment by PF4Public** [comment]
> Reworking our filter interface to fit the case where a character is composed of multiple codepoints, which doesn't appear to be very common at all, would definitely complicate things a little and doesn't seem worthwhile just yet.

I didn't even think of it. That makes sense, thanks for explaining.

**Comment by RocketMan** [comment]
LGTM.  Thanks for adding this!

**Comment by JerryCasiano** [comment]
@RocketMan 

Your welcome.

I'm leaving this open a little longer, just in case I introduced any weird bugs with these changes.

**Comment by PF4Public** [comment]
You did it! I've just built from 6401728461f937eebcbe750c73867ae2d9651f98 and everything seems to be fine, not obviously broken.

As a side note, I couldn't find [Pirate Flag](https://emojipedia.org/pirate-flag/), [Chequered Flag](https://emojipedia.org/chequered-flag/), [White Flag](https://emojipedia.org/white-flag/) and some [other "flags"](https://emojipedia.org/flags/). Are they worthy of inclusion? They seem to be using ZWJ and could completely break your filtering logic :)

**Comment by JerryCasiano** [comment]
Chequered and White flags are definitely there, those are single codepoint, search for flag and scroll through to see them.

Pirate and some of the other flags that use 2+ codepoints would definitely require completely re-thinking not just filtering but how we store codepoints and orthographies. So I think we'll let those go unsupported for now.

**Comment by PF4Public** [comment]
> Chequered and White flags are definitely there, those are single codepoint, search for flag and scroll through to see them.

Indeed, my mistake. But they don't appear in filtered flags.
