### ISSUE TITLE
.deb version?

### ISSUE THREAD

**Issue by jeffmcneill** [FontManager/font-manager#111]
Feature request: .deb build

**Comment by JerryCasiano** [comment]
Debian has font-manager in its repositories, probably a very outdated version as usual, but it is there.

There is a PPA at https://code.launchpad.net/~font-manager/+archive/ubuntu/staging for Ubuntu users and there is a debian folder in the root of the repository which anyone can use to build a .deb package themselves.

So I'm not sure what exactly you're requesting ?  But that's really about as far as I'm going to go.  

Sorry, but I'm not jumping through hoops in order to maintain or build packages for any particular distribution, especially not one which I don't even use.
