### ISSUE TITLE
Is the dependency vala needed?

### ISSUE THREAD

**Issue by Munzu** [FontManager/font-manager#126]
I just installed font-manager on my system. Unfortunately, it broke my default font because it installed vala as a dependency, which installs graphviz as a dependency, which again installs gsfonts as a dependency.
gsfonts comes with the Nimbus font. 

For some reason, when gsfonts was installed, it overrode my default font (which was Noto) to Nimbus. 

I tracked down the dependency chain of gsfonts and saw that it ended with vala, i.e. my package manager (pacman) told me vala wasn't actually required by any other package on my system. 

I ultimately fixed the problem by removing all orphaned packages on my system, which got rid of vala (this is just a temporary fix though since a font-manager update would probably just reinstall vala). 
As far as I can tell, font-manager still works without vala. 

Is the vala dependency maybe out of date?

Version info:

- Arch Linux 5.8.3-arch-1-1
- font-manager-0.7.8-2

**Comment by JerryCasiano** [comment]
> Is the vala dependency maybe out of date?

valac, the Vala compiler,  is required if you plan on compiling anything written in Vala.  It's not required to run the result.

But you should probably try to figure out why your system is selecting  a different font and address the root cause.

Or, you know, you could maybe just disable those fonts using something like, oh I don't know, font-manager maybe. ;-)
