### ISSUE TITLE
Command-line usage

### ISSUE THREAD

**Issue by btrspg** [FontManager/font-manager#127]
Hi there,

I found you developed a fantasy tool, but I wonder if I could use it in the command-line. So that I may include it in the Docker image and add fonts easily in the Dockerfile. 

Looking forward to your reply.
Many thanks.

Logan

**Comment by JerryCasiano** [comment]
I'm not very familiar with Docker or their build process and I'm not sure how you intend to use the application so I don't have a good answer for you.

Including the application in the image just to facilitate font installation during the creation process sounds like a bad idea. A bit heavy for that.

See `man font-manager` for available command line options.

Note that the whole purpose of the tool is to cater to people who prefer not to use the command line so options there are pretty limited. You can install, enable, disable fonts but not much else. There's no real configuration there and you can't select target directories.

I'm not opposed to enabling other options if they're useful but I would need to know more about what you actually need font-manager to do.

I'm closing this since it's not really a bug but feel free to continue the conversation here.
