### ISSUE TITLE
Issue with other flatpak apps with only active fonts

### ISSUE THREAD

**Issue by jrramosp** [FontManager/font-manager#168]
I have encountered the following issue when using the program version 0.8.3 installed from the PPA. When I try to use a font that is only activated, not installed, and I want to use it in a flapak program (Krita), it does not recognize it. If I use the same program in an appimage version, I don't have the same problem. If I install the font in the user folder the flatpak program recognizes it too.
Is there any way to get the font detected from the flatpak environment?

Translated with www.DeepL.com/Translator (free version)

**Comment by JerryCasiano** [comment]
The answer to this is... I don't know.

You may just need to give those applications access to the fontconfig folders/configuration on the host but I don't know anything about Flatpak. :-/

I'm not even sure where to point you in order to get that information. Sorry.

I am closing this since it's not an issue that we can fix on our end, at least I don't think it is.

It would be appreciated if you posted back if you find a solution so I can pass that info along to others.

Also, if it does turn out to be an issue that we can fix on our end feel free to reopen.

Thanks.

**Comment by PF4Public** [comment]
@Eonfge could probably help with this…

**Comment by JerryCasiano** [comment]
You know I just remembered someone else had this issue and a workaround.

See issue #133 there's an edit in the first post with the info you need.

I should probably note this in the Readme

**Comment by jrramosp** [comment]
The solution work really fine. You only need to add xdg-config/fontconfig in Filesystem → Other files for specific apps, if you are using the app Flatseal, or manually adding --filesystem=xdg-config/fontconfig when you launch the app you want to execute. Thanks you all

**Comment by JerryCasiano** [comment]
Thanks for reminding me about this issue.

I've added a note to the README about this.

**Comment by Eonfge** [comment]
@jrramosp  Hey, just to double check; You run into the problem that some other apps don't use the fronts that you installed using Font Manager?

If that is the case, make sure to file a bug-report at the appropriate project within Flathub:
https://github.com/flathub

This is really an issue of sandboxing working against Font Manager. The official location for fonts is in `xdg-config/fontconfig` but not all Flatpak packages have that properly configured.
