### ISSUE TITLE
Request: multi-select to compare fonts -or- filter "browse" view by style

### ISSUE THREAD

**Issue by akvadrako** [FontManager/font-manager#170]
Hello Jerry,

I would like to compare all the fonts in a collection; I see two ways to do this with font-manager, but both are less than ideal.

The browse view is pretty good, except I want to compare only the "regular" styles, not italic or bold. The regular versions are too far apart to compare them meaningfully. So if would be nice to filter them so only regular versions are displayed.

The compare view is what I want, except it seems like I manually need to select each font in my collection and press "+", which gets tiring quickly. If I could multi-select fonts and press "+" that would be ideal.

What do you think about either of these suggestions?

**Comment by JerryCasiano** [comment]
I think adding all the selected items to the compare list is probably the way to go here, that should be simple enough.

I'll enable it later today.

**Comment by JerryCasiano** [comment]
The last commit makes it so that all currently selected fonts get added to the comparison when the add button is clicked.

Still requires you to use the expand all button then ctrl + click to select individual styles if you're comparing anything other than regular. Regular is the default so in that case you can just rubber band select families without expanding.

Not ideal.

I'll need to think on what the best approach is for making this type of filtering more convenient without cluttering the interface any further. Probably going to require an option to use a flat listing instead of the normal grouped by family listing when the font list is filtered.

**Comment by akvadrako** [comment]
Thanks! I didn't even know about the `ctrl +` since I'm mostly interested in regular fonts.

A flat listing does seem to make the most sense. Someone can use the category selection to narrow down to say "Italic" and then select the italic versions for a collection.
