### ISSUE TITLE
Font-manager wont run

### ISSUE THREAD

**Issue by 1nformation** [FontManager/font-manager#201]
Hey, I have installed font-manager from the aur, and it refuses to run

I get the following output in terminal

```
[font-manager]:ERROR:../font-manager-0.8.4/lib/unicode/unicode-character-map.c:326:get_font_size_px: assertion failed: (priv->font_desc != NULL)
Bail out! [font-manager]:ERROR:../font-manager-0.8.4/lib/unicode/unicode-character-map.c:326:get_font_size_px: assertion failed: (priv->font_desc != NULL)
zsh: abort (core dumped)  font-manager 
```

I have the same result with font-manager-git

**Comment by PF4Public** [comment]
Could it be an aur packaging issue? All is fine on Gentoo:
![image](https://user-images.githubusercontent.com/10319700/106919035-cf51fe80-671a-11eb-90aa-cc3fed3ecf33.png)

**Comment by JerryCasiano** [comment]
> Could it be an aur packaging issue?

Could be.

I'm leaning towards a system specific issue on this one for now, until some more Arch users chime in that is.

It's easy to fix, just need to initialize to initialize that variable to a default font description. BUT I'd rather not workaround it without understanding it because that doesn't answer the question of why that assertion is not triggered on other systems...

That code hasn't changed in some time.

@1nformation 

Are all the dependencies provided by the core repo? Or are you using AUR versions of any of the dependencies?

**Comment by JerryCasiano** [comment]
@1nformation 

Now that I've had a chance to look at this, I don't think it makes any sense to have that assert there. 
Probably left over from debugging at some point. 

You'll need to build from Git as I don't plan on making another release unless a lot of users run into this issue.

I still wonder what's different about your system though...

Feel free to re-open this if you run into any other problems.

Thanks.
