### ISSUE TITLE
Two font styles always escaped while installing font family with 18 styles.

### ISSUE THREAD

**Issue by abhidesh128** [FontManager/font-manager#202]
While installing font family having 18 styles e.g Montserrat, Fira Sans, Work Sans (Google Fonts Versions downloaded from fonts.google.com) etc. font manager always escapes two styles : **ExtraLight italic & Regular italic.**

**How to reproduce :**

1. Download Montserrat (or any above mentioned) family from fonts.google.com.
2. Extract it in directory of your choice.
3. Open `font-manager`.
4. Click on the add button at top left, go to the directory where the fonts were extracted and select all the 18 files.
5. Click 'Open'.
6. `font-manager` will install only 16 fonts out of 18.

It is required to manually copy the missing files in the respective font directory in `~/.local/share/fonts/`.

**Screenshot :**

![image](https://user-images.githubusercontent.com/56992370/107662751-9bde1980-6cb0-11eb-9d18-1a3aff1c4266.png)

**System info :**
<pre>Distro : MX Linux 19.3 Patito Feo
Xfce version : 4.14.2
font-manager version : 0.7.3</pre>

**Comment by JerryCasiano** [comment]
So... you're using a version that was released almost 4 years ago.

There's been 11 releases since then!

I'm sorry but I don't provide long term support so in the future please ensure that you can duplicate the issue with the current version, otherwise any issues you run into need to be reported to your distribution and not here. It's unfortunate that your distribution ships such an outdated assortment of software but that is their choice and it should fall on them when their users run into issues not on the upstream project.

The current release not only installs all 18 variations but it also allows you to install fonts from the Google Fonts Catalog directly from within the application.  So the solution is simple -> update to the latest release.

Anyway, I hope you don't take this response the wrong way, I'm not trying to be rude it just is what it is.

![FiraSans](https://user-images.githubusercontent.com/11490124/107715867-29fcd480-6c9e-11eb-8abe-c97e267ff53a.png)

![GFC](https://user-images.githubusercontent.com/11490124/107715921-3e40d180-6c9e-11eb-8d45-53d99498a6e7.png)

**Comment by abhidesh128** [comment]
I updated my `font-manager` by installing it via flathub. That solved my issue. Thanks for integration of Google fonts...! It's very handy.
