### ISSUE TITLE
Show waterfall view in geometric progression

### ISSUE THREAD

**Issue by PF4Public** [FontManager/font-manager#230]
As discussed in f2faedda5628198f48143fc47651f840535fd9dd
Fonts could be better (and flexibly customizable) represented in waterfall if ordered in a [geometric progression](https://en.wikipedia.org/wiki/Geometric_progression) by size.
It could ideally have following user-configurable options:
* First point
* Common ratio
* Number of points ~/ maximum value~

At its extreme it could easily cover big and small in four steps:
| Parameter | Value |
| --- | --- |
| First point | 10 |
| Common ratio | 2 |
|Number of points| 4 |

[10 20 40 80](https://www.wolframalpha.com/input/?i=10,+20,+40,+80,...)

Or be a little bit gentler in 10 steps:
| Parameter | Value |
| --- | --- |
| First point | 10 |
| Common ratio | 1.2 |
|Number of points| 10 |

[12 14.4 17.28 20.736 24.8832 29.8598 35.8318 42.9982 51.5978 61.9174](https://www.wolframalpha.com/input/?i=10+1.2%5En)

In Font-Manager you could probably round these values up to the closest integer.

I did some monkey-coding to show how it could look like.
* Original version:
![image](https://user-images.githubusercontent.com/10319700/127204699-bcd6cb0a-3672-4a1a-bf6d-59eb357fa851.png)

* Progressive one (pun intended) **1.2**:
![image](https://user-images.githubusercontent.com/10319700/127204359-c4dfafe3-7df9-4b93-b6da-6c65ead74527.png)

* Progressive one **1.5**:
![image](https://user-images.githubusercontent.com/10319700/127205059-4c5a5bfa-64f3-4e7a-af68-596740953407.png)

**Comment by JerryCasiano** [comment]
Got a chance to play with this yesterday. I've uploaded a branch with the initial changes. It's seen very little testing but seems to work well.

Feedback is much appreciated. 

If you're just running from the build directory you'll need to install and compile the schema file due to additions.

**Comment by PF4Public** [comment]
Just built it, works fine.
I have only 2 notes:
* If selecting another font for the first time, there is a delay between a click and the time this font gets highlighted. Looks like it prepares a list of fonts to render, renders it and only after that selection event got acknowledged. This makes it feel kind of sluggish. Best would be if the selection event got first acted upon by selecting a new font and only then all the rendering took place.
* I cannot explain it better, but it feels no me more natural to first set the `initial point`, then `scaling` and only then the `maximum point`. I mean it would be more natural to order settings this way.

**Comment by JerryCasiano** [comment]
I kind of need to know what settings you're using for the waterfall and how many fonts you have available to reproduce what you're seeing. With the default settings it takes about 5k fonts before I start seeing some lag on my system (an older thinkpad).

> If selecting another font for the first time, there is a delay between a click and the time this font gets highlighted.

This is due to someone stating that doing otherwise is ["dangerous"](https://github.com/FontManager/font-manager/issues/46).

> Looks like it prepares a list of fonts to render, renders it and only after that selection event got acknowledged. This makes it feel kind of sluggish. 

So...

What happens when you select a font and you are viewing the waterfall preview is that we check what sample string to render and generate the "waterfall" in a loop. The amount of time taken to generate the waterfall is not worth worrying about, it's a fast enough for loop and if the sample string didn't change then we don't even do that we just change the font description. The amount of time taken to decide what sample string to draw can vary depending on a few factors but it's not too bad in general. It is an area that causes some slowdown though. Not sure how to make this faster while still displaying samples that makes sense for the font selected.

After that happens, it's all about how quickly the GtkTextview can render the given string in the sizes requested. This is actually the reason why the last release defaulted to 48 pt as the max to render because the larger the font size gets the slower the textview is to render it.

For comparison, switch to the interactive preview or the body text preview and compare the difference. I get no lag there whatsoever regardless of number of fonts available.

> Best would be if the selection event got first acted upon by selecting a new font and only then all the rendering took place.

We can probably do that, I mean, we used to do that but changed it due to #46

**Comment by PF4Public** [comment]
Please see the screencast below to see what I mean. I supposedly have 251 fonts and click through them in screencast. Unfortunately, I couldn't capture mouseclicks, but be assured, that I click immediately and wait. 

Notable thing is that `EB Garamound Initials` is immediately highlighted and the rendering takes place after. Unlike others! The only difference I can think of is that it is the lightest of them all! One could conclude that this delay depends on the filesize (although this laptop has SSD). In the end I click between two fonts, which shows no delay whatsoever. Could it be a CPU-cache manifested issue?

https://user-images.githubusercontent.com/10319700/128599061-5a6dc76e-e507-4113-a458-66ed0179158d.mp4

**Comment by JerryCasiano** [comment]
> Could it be a CPU-cache manifested issue?

I think you're hitting the spot where we update the sample string, probably due to different system language.

Try the last commit when you get a chance and see if that improves things for you.

> PS: You didn't write anything with respect to the third point. Is it difficult to implement?

Not really.  It's not difficult to implement I'm just not sure whether people will find it more confusing or not and what it should actually default to. I think 10 points is probably not enough, in my opinion the "waterfall" needs to cover the entire view on most screens out there, a large blank spot at the bottom looks wrong to me so maybe we need to default to 48?  Since we'll probably also have to default to linear scaling.

But I don't think it's a bad idea. It would hide three settings unless the user was interested in changing them and that's a good thing.

**Comment by JerryCasiano** [comment]
@PF4Public 

That last commit is just a "rough" draft so we have something to look at and play with.

We can easily experiment with and adjust the predefined options.

**Comment by PF4Public** [comment]
> Try the last commit when you get a chance and see if that improves things for you.

No improvement, with that commit `EB Garamound Initials` lags in a similar way as others

I've run it under sysprof doing the same clicking:

![image](https://user-images.githubusercontent.com/10319700/128606852-e73c0f0b-3b83-42b7-ba79-f8b66e28c5bb.png)

It seems to be spending time in `fontconfig`.  Why would it be comparing families?

BTW I can reproduce this issue with version 0.8.7 and max-font setting 48. So it is unrelated to these changes. Sorry for mixing things.

> That last commit is just a "rough" draft so we have something to look at and play with.

That is a solid improvement :) I'd suggest calling options "Up to * points (* Common Ratio)". "60 points (1.1 Common Ratio)" looks confusing: _is it about 60 fonts as in "total amount"? is it a single font? 60 points of what?_ and so on.

>>Best would be if the selection event got first acted upon by selecting a new font and only then all the rendering took place.

>We can probably do that, I mean, we used to do that but changed it due to #46

Unfortunately I couldn't comprehend the reasoning behind "being dangerous", so I will trust you on this one and leave it for you to decide where this change worth the trouble.

**Comment by JerryCasiano** [comment]
> It seems to be spending time in fontconfig. Why would it be comparing families?

No idea. It looks like that happens in Pango internals.

We don't ever need to compare families using fontconfig but Pango probably has to.

> Unfortunately I couldn't comprehend the reasoning behind "being dangerous"

Me either. ;-)

The previous commit kind of reverted that change so kind of sucks that it didn't make any difference for you.

**Comment by PF4Public** [comment]
I think I can see (at least one kind of) the "danger". Look closely at the Garamound family and below:

https://user-images.githubusercontent.com/10319700/128611116-dcc7a0c4-898f-421a-8c0e-a36ca0f59989.mp4

For a brief moment it renders new font with the old string, then changes the string. I wouldn't call it a really dangerous thing, but it is definitely a visual glitch. Even annoying one :) So, let's admit, at least due to this, you shouldn't revert that commit :)

Playing with it further I see that going downwards every step gives me a lag, but should I change the direction and revisit the fonts, which I have already seen, there is no lag for a 4 to 5 fonts. Why would it be so?

**Comment by JerryCasiano** [comment]
> Playing with it further I see that going downwards every step gives me a lag, but should I change the direction and revisit the fonts, which I have already seen, there is no lag for approximately 4 to 5 fonts. Why would it be so?

Sounds like they're being cached. We don't do any caching as far as that goes, we simply ask GTK to render a certain string in a certain font at a certain size.  It's very likely Pango is keeping a certain amount font files cached.

What I don't understand is why I'm not seeing the same issue on my system. I even changed the language to Russian and loaded up 1k fonts to see if I could reproduce but there really wasn't any significant lag.

**Comment by PF4Public** [comment]
I tried commenting code and rebuilding font-manager to find the one that is responsible for the lag.
Turns out without this one font selection switches immediately:
https://github.com/FontManager/font-manager/blob/f75ad5c46dc1b611eb39e64939dee2400cfdca74/lib/common/font-manager-font-preview.c#L452-L456

Is there something heavy happening?

I then tried reorganising this function:
https://github.com/FontManager/font-manager/blob/f75ad5c46dc1b611eb39e64939dee2400cfdca74/lib/common/font-manager-font-preview.c#L682-L693

by decorating various functions with `g_idle_add((GSourceFunc)`, but this didn't help with the lag. Not even decorating `update_font_description`. Only commenting `g_object_set(` removes the lag, but also removes the functionality with it :) Could it be, that `g_object_set(` somehow affects UI-thread no matter how it was called? Maybe there is more code behind this call, that I miss?

**Comment by JerryCasiano** [comment]
> Is there something heavy happening?

Not directly, but indirectly? Yes, probably.

g_object_set just allows you to set multiple properties on a GObject, so there isn't really anything heavy about it. How heavy that call actually is depends on what happens next i.e. what the object does in response to having those properties changed.

In this case we're changing properties on a GtkTextTag which causes the GtkTextView displaying the preview to update and based on your testing you've pretty much confirmed that is indeed where the slowdown is happening.

> This lag does not happen on other tabs and with Preview and Lipsum modes. Only if Waterfall is open. It also does not depend on the number of font points in Waterfall.

So... could be that we've hit an edge case with GtkTextView.  Either rendering the same font at different sizes is expensive or rendering the size point in a different font at a different size on the same line is expensive.

Since you're experiencing this consistently, please try again after modifying the following function.

```
static gboolean
generate_waterfall_line (FontManagerFontPreview *self)
{
    GtkTextIter iter;
    GtkTextBuffer *buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(self->textview));
    GtkTextTagTable *tag_table = gtk_text_buffer_get_tag_table(buffer);
    gint i = current_line;
    //g_autofree gchar *size_point = NULL;
    g_autofree gchar *line = g_strdup_printf("%i", i);
    //size_point = g_strdup_printf(i < 10 ? " %spt.  " : "%spt.  ", line);
    gtk_text_buffer_get_iter_at_line(buffer, &iter, i);
    //gtk_text_buffer_insert_with_tags_by_name(buffer, &iter, size_point, -1, "SizePoint", NULL);
    if (!gtk_text_tag_table_lookup(tag_table, line))
        gtk_text_buffer_create_tag(buffer, line, "size-points", (gdouble) i, NULL);
    //gtk_text_buffer_get_end_iter(buffer, &iter);
    g_autofree gchar *pangram = g_strdup_printf("%s\n", self->pangram);
    gtk_text_buffer_insert_with_tags_by_name(buffer, &iter, pangram, -1, line, "FontDescription", NULL);
    if (self->waterfall_size_ratio > 1.0) {
        gdouble next = current_line * self->waterfall_size_ratio;
        current_line = self->waterfall_size_ratio > 1.1 ? floor(next) : ceil(next);
    } else
        current_line++;
    return current_line > self->max_waterfall_size ? G_SOURCE_REMOVE : G_SOURCE_CONTINUE;
}

```

If that helps, it means that the slowdown is caused by rendering two different fonts at different sizes at the same time on every line.

That would be the best case scenario since we can easily toggle that on / off if we want to. :-)

If that doesn't help then it means that simply rendering a bunch of different sized lines is the issue and GtkTextView is just not suitable for this use case. This is worst case scenario. :-(

**Comment by PF4Public** [comment]
Thank you for your help with it. Leaving only one font-family in textview didn't have significant impact on lag. But it became obvious, that this lag is only present if font file is bigger than some value. So I suppose, pango or fontconfig need more time to digest bigger (by filesize) fonts and if we allow this to happen while click event is dealt with, we get a lag in response. I tried moving `update_font_description` or `g_object_set(` into a separate thread, but unfortunately my programming skills are limited (and especially my GTK knowledge). I'm not a programmer anyway :) So all my attempts failed miserably. But in the end I've got an idea…

After countless attempts I managed to come up with a "clever" solution to my issue :)

https://user-images.githubusercontent.com/10319700/128727918-1ee07260-44ab-42b2-a47a-974cadad1426.mp4

```diff
@@ -486,7 +486,7 @@ update_sample_string (FontManagerFontPreview *self)
             g_clear_pointer(&self->restore_preview, g_free);
         }
     }
-    if (pangram_changed && self->mode == FONT_MANAGER_FONT_PREVIEW_MODE_WATERFALL)
+    if (self->mode == FONT_MANAGER_FONT_PREVIEW_MODE_WATERFALL)
         generate_waterfall_preview(self);
     return;
 }
@@ -496,6 +496,7 @@ update_font_description (FontManagerFontPreview *self)
 {
     g_return_if_fail(self != NULL && self->font_desc != NULL);
     GtkTextBuffer *buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(self->textview));
+    gtk_text_buffer_set_text(buffer, "", -1);
     GtkTextTagTable *tag_table = gtk_text_buffer_get_tag_table(buffer);
     GtkTextTag *font_description = gtk_text_tag_table_lookup(tag_table, "FontDescription");
     g_return_if_fail(font_description != NULL);
```

I thought to myself: if updating tags on a full buffer lags, what happens if the buffer is empty? I think this way this lag didn't vanish, rather it is moved to a separate thread, where it doesn't affect the UI at least. 

I hope that you can improve this fix and incorporate it into FontManager.

**Comment by JerryCasiano** [comment]
Nice!

I think it's probably perfect as is, might make it a preference though, don't know yet need to use it this way first.

> I thought to myself: if updating tags on a full buffer lags, what happens if the buffer is empty? 

I didn't even consider this...

We do this when sorting treeviews because otherwise they lag also.

> I'm not a programmer anyway :) 

Neither am I really... 

Shh! Don't tell anybody.

**Comment by PF4Public** [comment]
So I guess we may now consider this feature implemented and the lag is also fixed…

**Comment by JerryCasiano** [comment]
Yup. 

This worked out very well.

I'll merge these changes later.
