### ISSUE TITLE
assert: font_manager_google_fonts_sample_row_from_item

### ISSUE THREAD

**Issue by spezialspezial** [FontManager/font-manager#249]
**Describe the bug**
I encountered an issue managing Google Fonts. On specific families, Genos for example, I get ->

```
(font-manager:146472): [font-manager]-CRITICAL **: 14:33:43.374: font_manager_google_fonts_sample_row_from_item: assertion 'item != NULL' failed
(font-manager:146472): GLib-GObject-CRITICAL **: 14:33:43.374: g_object_is_floating: assertion 'G_IS_OBJECT (object)' failed
(font-manager:146472): Gtk-CRITICAL **: 14:33:43.374: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
(font-manager:146472): Gtk-CRITICAL **: 14:33:43.374: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
(font-manager:146472): GLib-GObject-CRITICAL **: 14:33:43.374: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(font-manager:146472): GLib-GObject-CRITICAL **: 14:33:43.374: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
It does not crash the app but might be worth checking out.

**To Reproduce**
1. Manage -> G -> find Genos
2. Click Genos
3. See stdout
5. Click a different family
6. ->
 ```
(font-manager:146472): Gtk-CRITICAL **: 14:43:41.787: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```

**System Information**
 - OS: Ubuntu 20.04.3
 - GNOME 3.36.8
 - Font Manager version 0.8.7.202111200246~ubuntu20.04.1

**Stretch Goal**
Out of curiosity. Where in the vala source is the first assert generated?

**Comment by JerryCasiano** [comment]
@spezialspezial 

It's kind of a cascade.

The assert itself is generated in a closure which itself is generated by [Language.vala:162](https://github.com/FontManager/font-manager/blob/master/src/font-manager/web/google/Language.vala#L162)

Whenever the language sample model changes SampleRow.from_item is called repeatedly, once for each entry in the model, so that it generates a widget for each. Our problem was that we didn't account for when a language is not in that list. Oops...

Google Fonts itself actually doesn't list this language or a sample for it, so I just used a sample from our standard orthographies.

In any case, if you look at the last commit, from now on when we encounter a language  that's not in the list we generate a widget which contains a message to the user to file an issue requesting an update rather than generating a broken list and spamming the terminal.

Thanks a lot for catching and reporting this !

And again the PPA should update within a day or so.

**Comment by JerryCasiano** [comment]
I'm sorry, I just realized I may not have answered your actual question.

You asked where in the Vala code the assert was generated. 

Vala automatically generates checks for arguments and return values so if one of those is not marked as nullable by appending a ? to it then Vala will output something like

    g_return_if_fail(something != NULL);

in the generated C code.

**Comment by spezialspezial** [comment]
Ah, pretty interesting, thanks. Haven't used Vala before, looks nice and tidy.
