### ISSUE TITLE
Fira Code Symbol is weirdly rendered

### ISSUE THREAD

**Issue by PF4Public** [FontManager/font-manager#283]
I suppose, it is due to ligatures:
![image](https://user-images.githubusercontent.com/10319700/153854543-a3b0ed27-00ed-4e2a-aee9-17cb37fb49b5.png)
![image](https://user-images.githubusercontent.com/10319700/153854609-c7548001-e5b1-4a14-a8aa-8f55a61abeb8.png)

PS: BTW have you considered adding ligatures to symbol table? Like "fi" "ft" "fft" and so on.

**Comment by JerryCasiano** [comment]
Do you have a link to the file?

I assume you are talking about the fonts available at https://github.com/tonsky/FiraCode?

I've installed the ttf version of those but didn't get the same result.

**Comment by PF4Public** [comment]
I think it must be this file: https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip

**Comment by JerryCasiano** [comment]
Yeah, that's the one. It doesn't seem to be included in the regular download for whatever reason.

If you right click in the character map it's clearly related to positioning but I don't believe we can actually do anything about it. 

gnome-font-viewer renders it the same way and so does LibreOffice. So that means GTK / Pango won't work and whatever rendering method LO uses won't either. Didn't check KDE, don't have it installed.

But unless you know of a graphical program that renders this file correctly I think it's not usable. :-/

**Comment by PF4Public** [comment]
Well, it is another wontfix then.
