### ISSUE TITLE
Port to GTK 4

### ISSUE THREAD

**Issue by JerryCasiano** [FontManager/font-manager#286]
### Internal
 - [x] Port all user interface elements to GTK 4
 - [ ] Test all user interface elements

### External 
 - [x] Official [WebKit GTK 4](https://bugs.webkit.org/show_bug.cgi?id=210100) release available on most mainstream distributions
   - Affects Google Fonts integration

## 
GTK 4 is very different from previous versions and will likely take quite a bit of effort and time to switch to.  

The GTK 4 migration guide is [here](https://docs.gtk.org/gtk4/migrating-3to4.html).

The GTK 4 documentation is available [here](https://docs.gtk.org/gtk4/).

Interested users are encouraged to check out the [wip-gtk4](https://github.com/FontManager/font-manager/tree/wip-gtk4) branch.

**Comment by PF4Public** [comment]
Will it somehow affect the UI? Changes in the UI?

Are there any improvements in handling ellipsis in tables? https://github.com/FontManager/font-manager/issues/210#issuecomment-816958603

**Comment by JerryCasiano** [comment]
> Will it somehow affect the UI? Changes in the UI?

The answer is... probably. 

It will certainly affect the UI aesthetically, most changes will likely be subtle but some could be major.

As far as functionality or features go, I would say no. Regression is not really acceptable at this point in my opinion. That happened with the previous port and though I think we're better off for it, it took a long time to get there.

> Are there any improvements in handling ellipsis in tables? https://github.com/FontManager/font-manager/issues/210#issuecomment-816958603

Probably not initially, I'm guessing a one to one port is more likely at first just to get something working and verify it's working right.

But I haven't gotten to the point of testing the new list widgets yet to know if we can use them instead of a tree view. If they can provide the same functionality then switching to them should resolve that. And that might happen right off the bat if they work well for our purposes.

**Comment by PF4Public** [comment]
Are support of GTK 3 and GTK 4 mutually exclusive? Will font-manager continue be buildable for some time against gtk3 as well as against gtk4?

**Comment by JerryCasiano** [comment]
> Are support of GTK 3 and GTK 4 mutually exclusive? 

Very much so. :-(

> Will font-manager continue be buildable for some time against gtk3 as well as against gtk4?

The GTK 3 version will remain as-is at this point. It'll be deprecated once a GTK 4 version is released. Probably move it to a separate branch.

For now, support for the current version amounts to fixing build failures or major bugs but definitely not working on any new features, improvements or major changes anymore as far as GTK 3 goes. Might provide this minor level of support for quite some time, no sure yet, we'll see if it's needed.

That switch is not going to actually happen anytime soon, I don't think it is anyway, still a long way from a working complete port unfortunately.

I do have the font-viewer component working on 4 now and will probably push those changes to the testing branch soon. The main application though is nowhere close.

**Comment by fossfreedom** [comment]
Whilst moving to gtk4 is understandable will you be embracing libadwaita as well?

For Ubuntu Budgie we are looking very closely at font-manager to make it a default install app... libadwaita comes with its own styling issues that we are trying to avoid for our user base.

**Comment by JerryCasiano** [comment]
> Whilst moving to gtk4 is understandable will you be embracing libadwaita as well?

No.

Specifically for that reason. I dislike adding dependencies as it is let alone when they force a certain styling on the user. 

Though we may end up having to mimic certain elements from Adwaita, so we don't stick out like a sore thumb on GNOME, if we do go that route we'll definitely make that portion of the stylesheet user configurable through dconf ( load / don't load ) so you'll be able to override that if we don't find a way to just do the right thing.

Also, making sure the application integrates well with other GTK based desktops, as much as possible, is more of a goal than it was previously for me so don't hesitate to give feedback on that front.

**Comment by JerryCasiano** [comment]
@PF4Public 
@Eonfge 
@alerque 
@ehaupt
 
Would appreciate some feedback regarding changes to the application id.

This was brought up in #122, while at the time I didn't think it was worth the effort I'm starting to think it is something that's worth considering for the 0.9 release. There are so many changes going into this release anyway...

So the question is how would this affect packagers? Is this a big deal or not really?

I don't think it'll have much effect on users as we can migrate the old settings and even offer to reset dconf for them.

But if it's going to cause major issues for packagers then we can simply leave well enough alone.

What say you?

Note : There is still quite a bit of work left before 0.9 but most of the interface has been ported and things are now starting to come together.

**Comment by alerque** [comment]
As far as Arch Linux packaging is concerned it won't make much difference. We do our best to ignore the ridiculous and un-ergonomic app ids anyway. Our package is just `font-manager` and installs a binary of the same name. Many of the support files under the hood had the ID scheme in them, but nothing user facing and presumably would rotate out to whatever the new ID is. The only inconvenience would be to end users who need to migrate their settings.

**Comment by Eonfge** [comment]
> We do our best to ignore the ridiculous and un-ergonomic app ids anyway. 

@alerque That's not very forward looking. It's perfectly possible that multiple companies have similar apps. By using the url naming scheme, you can ensure that users always see the difference between packages. `flatpak search proton` returns like 10 applications with 'Proton' in the name, so something to ensure uniqueness in the long run is really important. But I digress, let Arch users embrace the freedom and all its caveats.

---

So yeah, I think it's important and I agree with the standard. For reference, Android and IOS applications do the same because they too have boatloads of almost identical apps. Some unique name is necessary, and making it web-url based makes it more clear to end-users what goes on.

That brings us to the application id. The standard points towards something like 
- `io.github.fontmanager.font-manager`
- `io.github.fontmanager.font-viewer`

You can also drop the io-tld and go with 
- `com.github.FontManager.font-manager`
- `com.github.FontManager.font-viewer`

The more interesting part is, that you currently use `org.gnome.XXX` which is something you're grandfathered into, but which is against the Trademark policies of GNOME. No big problem if you ask me, but they would appreciate the change.

From Flathub's perspective it's easy. The infrastructure is in place to migrate existing users, and I've done it before. If you change the app-id, I'll gladly follow you.

## Guides
- https://docs.flatpak.org/en/latest/conventions.html#application-ids
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic
- https://developer.gnome.org/documentation/tutorials/application-id.html

**Comment by alerque** [comment]
> let Arch users embrace the freedom and all its caveats.

This isn't an Arch Linux issue, look around: almost every Linux distro out there uses plain package names. Arch, NixOS, Debian, Ubuntu, Fedora, Slackware, OpenSUSE, RHEL, CentOS, Gentoo, Alpine, Void, ALT, AOSC, Deepin, PLD, NetBSD, OpenBSD, FreeBSD, ...,  — in fact the only one I can find that uses that kind of namespacing with any regularity is ElementaryOS. In other words my comment about Arch will be about the same for [all the distros that package this app](https://repology.org/project/font-manager/versions).

I understand what the IDs are for, but I don't think they are as effective as you think and they are not user friendly at all! There used to be this calculator app that I liked, but I literally gave up using it because I couldn't remember the stupid domain name to even run it from the CLI and I kept forgetting to alias a sane command name.

In the mean time most users never see the whole ID: the app stores just show they a name field which now has the added disadvantage of not being Unique. I know how Android apps look on disk, but have you ever searched for a common name and wondered which one of the ten identical name projects you actually wanted? The app id scoping is allowing you to install any/all of them but it doesn't help users know which are which, in fact it makes it worse by not requiring unique names. At least in 95% of *nix package managers package names are unique and don't change much.

**Comment by Eonfge** [comment]
@JerryCasiano `com.github.FontManager` is ironically one of the view Application-ids that's not possible: It would imply that the application is made by Github themselves. `com.github.FontManager.font-manager` would indicate that it's a third-party product who just happens to host at Github.

Funnily enough, this rule is fairly new. I still maintain a few applications grandfathered into the old format like `com.github.Flacon` or `io.github.dosbox-staging` but those should also be migrated over time.

**Comment by PF4Public** [comment]
@JerryCasiano As of now, is wip-gtk4 branch usable or still largely experimental?

**Comment by JerryCasiano** [comment]
It's not usable. 

Most of the components are there and you can play with them but unfortunately a lot of features are still missing.

On the upside, I am starting to put it all together but it is slow going.

**Comment by JerryCasiano** [comment]
@PF4Public 

The last commit to the WIP branch allows building the application in its current state.

In case you want to get a better feel for current status. A lot of things work, some things don't and a lot of things are still not implemented. It also requires that a database already exists in order to run. But it should build and run.

**Comment by PF4Public** [comment]
@JerryCasiano Are databases compatible? Should one have a testing one for wip-gtk4 and a separate one for normal version?

**Comment by JerryCasiano** [comment]
Database layout is still compatible for now.

If you haven't run the previous version before or haven't run it in a while you can run build/tests/updatedb before running src/font-manager/font-manager to create or update a database for testing.

**Comment by JerryCasiano** [comment]
Not to abuse this thread but since a few people who package have responded here...

I'll be tagging 0.8.9 in the next week or two. So any feedback on the latest commit is appreciated as it will be the last release for GTK 3. While serious bugs *might* get patched and tagged in GIT with micro versions I don't intend to do anymore actual releases.

The GTK 4 port is long overdue and pretty much there. Just minor details left to sort out at this point and I intend on releasing it at the end of summer at the latest before I go on vacation again.

**Comment by PF4Public** [comment]
@JerryCasiano Which one do you mean specifically: 9c52ed802841eed2bd9ed4f1c7d662dd94a112dc or 4c15fe6c8b74e08cbb29fc192ae555f4abadf7e9?

**Comment by JerryCasiano** [comment]
The latest one. 

Which ever happens to be the latest commit will end up being the release.

I'm just hoping for no blockers.

**Comment by barracuda156** [comment]
Please retain compatibility with GTK3 by the way, otherwise it will break it on some platforms.

**Comment by JerryCasiano** [comment]
@barracuda156 

Unfortunately that is not going to happen. 

0.8.9 barring some major issue is the last release targeting GTK 3

**Comment by barracuda156** [comment]
@JerryCasiano I have seen quite a number of software using GTK versions interchangeably. Is here something special here which makes that problematic?

**Comment by JerryCasiano** [comment]
Yes.

I have zero interest in supporting two mostly incompatible versions of GTK. 

If you want to volunteer to make that happen I'm happy to review pull requests against the work in progress branch.

**Comment by PF4Public** [comment]
@JerryCasiano So GTK 4 support is ready and fully functional?
