### ISSUE TITLE
Support SVG for OpenType fonts

### ISSUE THREAD

**Issue by bagnaram** [FontManager/font-manager#288]
**Is your feature request related to a problem? Please describe.**
Support to preview SVG for OpenType color glyphs as outlined in the Freetype2 support would be a great addition.

**Describe the solution you'd like**
Ability to view color glyphs in SVG fonts. Currently the font display blank glyphs, however support is available in Mozilla.

**Describe alternatives you've considered**
Viewing fonts in Mozilla is currently the only support besides Freetype2

**Additional context**

Support for SVG in OpenType has been added to Freetype2: https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/122

**Comment by JerryCasiano** [comment]
You need to file this request with Pango, which is the component used to render text in GTK applications.

While technically, yes, we could do our own drawing and render font formats which are otherwise unusable on your desktop that doesn't seem to make much sense.

The goal is to show you exactly what the font will look like if you try using it on your desktop in other applications, in this case GTK applications. Showing you what the font would look like if only it was actually supported by your desktop applications is definitely not a goal. 

That would only serve to confuse users if we rendered the font perfectly but then when they actually tried to use it they got tofu instead.


As said earlier I suggest you bring this request to the Pango developers as that benefits the entire ecosystem.

Thanks for your interest.
