### ISSUE TITLE
Display of fallback character

### ISSUE THREAD

**Issue by noraj** [FontManager/font-manager#290]
**Describe the bug**

I installed font-manager to preview unicode character support for various fonts. But font-manager seems to display a custom fallback character for character not present in the font instead of displaying the fallback from the font.

**To Reproduce**

1. Go to the _browse_ view
2. Write an uncommon unicode char in the preview input

**Expected behavior**

Display the fallback character from the font.

Eg. with DaFont, the character between the to `a` is a unicode character that is not supported by the fonts:

![font_render](https://user-images.githubusercontent.com/16578570/158566797-908771ab-e195-44d2-bb67-ef5b3a9d5531.png)
![font_render2](https://user-images.githubusercontent.com/16578570/158566802-872f866f-e654-45e6-96cc-582274bfae03.png)

Another example on Fonts.com

![image](https://user-images.githubusercontent.com/16578570/158569329-fea3dc2c-82aa-48c0-9457-690cbcd48dab.png)
![image](https://user-images.githubusercontent.com/16578570/158569424-bb05b697-2a7f-401e-a46c-95c3a712a2e4.png)

**Actual behavior**

Unsupported characters are displayed as a square/rectangle with the codepoint displayed in it.

![image](https://user-images.githubusercontent.com/16578570/158567320-0c2e139b-397a-47c6-bb62-b3c12a9d7fec.png)

This is handy in some case but it does not allow to see the fallback from the font or how it will really display in applications. I think there should be a _Native fallback_ option that can be on or off.

**System Information**

 - OS: ArchLinux
 - Desktop Environment KDE
 - Font Manager version 0.8.8
 - Font Manager installation method [pacman](https://archlinux.org/packages/community/x86_64/font-manager/)

**Comment by noraj** [comment]
In real life application (here libre office writer)  this is how fonts renders unsupported characters :

Anonymous Pro

![image](https://user-images.githubusercontent.com/16578570/158571803-976a2493-5d05-4f26-887f-42797e44522d.png)

Fira Code

![image](https://user-images.githubusercontent.com/16578570/158571868-5299d351-119b-4f04-80f1-d32c8600b7a8.png)

Inconsolata

![image](https://user-images.githubusercontent.com/16578570/158572018-b37e6e44-0c6c-4f6b-8c79-40186e6466f7.png)

**Comment by JerryCasiano** [comment]
Sorry, but I don't think that's going to happen.

I also don't think that is expected behavior for a font manager.

All the examples you listed aside from the last one in LibreOffice do the exact same thing, while the presentation may be different, they make it clear that the font does not provide that particular character, and that's for good reason. 

Feel free to comment out the relevant lines and recompile if you like

https://github.com/FontManager/font-manager/blob/b31cf1241af884e9d30cddfc2ffc4860bd11589b/lib/common/font-manager-font-preview.c#L529

https://github.com/FontManager/font-manager/blob/b31cf1241af884e9d30cddfc2ffc4860bd11589b/lib/unicode/unicode-character-map.c#L179

https://github.com/FontManager/font-manager/blob/b31cf1241af884e9d30cddfc2ffc4860bd11589b/src/font-manager/FontList.vala#L217

**Comment by noraj** [comment]
> they make it clear that the font does not provide that particular character, and that's for good reason.

Why different fonts have a different fallback character if it is not provided by the font? Or I'm misunderstanding the behavior? Can you explain please?

I understood a font was defining a fallback [(last resort) glyph](https://www.figma.com/fr/blog/when-fonts-fall/).

> At some point, you have to draw the line. That line is one last glyph. It comes with a technical name, .notdef, and the dot is there to signify it’s unlike any others. .notdef is a glyph of last resort, one to be used when a font is asked for a character its designer did not bother to draw.

So I wanted to see the `.notdef` glyph.

I think commonly the behavior is:

1. **Use a fallback font** where the unsupported glyph not present in the original font may be present
2. If no fallback font has the glyph, then use the `.notdef` glyph from the original font.

As far as I understand, the `.notdef` glyph is mandatory in a font. In Font Manager preview of course there will be no fallback font defined, so unsupported glyph should be rendered with the `.notdef` glyph from the font. It seems that Font Manager is ignoring the `.notdef` glyph (because "fallback" attribute is set to false in the code) and force using a specific fallback font like [GNU Unifont or Unicode BMP Fallback font](https://en.wikipedia.org/wiki/Fallback_font).

**Comment by JerryCasiano** [comment]
> As far as I understand, the .notdef glyph is mandatory in a font. 

And as you can see from the examples you provided above, it could be defined to anything, a blank space, a box, some custom glyph or any other glyph in the font.

A blank space is not what I would consider a good choice, it's not as obvious as the standard "tofu" character that GTK / Pango currently uses and most users will recognize immediately.

https://docs.microsoft.com/en-us/typography/opentype/spec/recom#glyph-0-the-notdef-glyph

Several of the examples you posted don't adhere to those recommendations, making them less than useful.

> In Font Manager preview of course there will be no fallback font defined, so unsupported glyph should be rendered with the .notdef glyph from the font. 

What exactly is the benefit of this? How is it useful?

What am I missing here? Why would users care what the actual .notdef glyph defined in the font file looks like?

> So I wanted to see the .notdef glyph.

Not enough of a reason for me.

Now, if you're prepared to make the required changes I'm more than happy to review a pull request.

> It seems that Font Manager is ignoring the .notdef glyph (because "fallback" attribute is set to false in the code) and force using a specific fallback font like [GNU Unifont or Unicode BMP Fallback font](https://en.wikipedia.org/wiki/Fallback_font).

The application doesn't do anything special in regards to font rendering. This is intentional. Rendering is handled entirely by GTK. The application is first and foremost a GTK font manager and is intended to be WYSIWYG in terms of font rendering with regards to GTK applications. We disable font fallback because a font manager should not simply substitute characters from a different font in previews, obviously, but we don't force anything, what gets rendered is up to the GTK stack.

**Comment by noraj** [comment]
> What exactly is the benefit of this? How is it useful?
> 
> What am I missing here? Why would users care what the actual .notdef glyph defined in the font file looks like?

Because it will be the glyph use in real life applications such a Libre Office, VTE (terminals), file explorers, virtually any app on the system. So user may want to know if a font have a proper `.notdef` glyph or if the font is using something to fancy or a blank and would avoid to use that font.
Also it is a glyph that is part of the font so why hide it?

> Now, if you're prepared to make the required changes I'm more than happy to review a pull request.

Yeah I'm an open source tool writer too so I sometimes answer that too. But the reality is I code in Ruby and I don't know a thing about C so unfortunately I'm not able (I don't have the skill) to PR on this project.

> The application doesn't do anything special in regards to font rendering. This is intentional. Rendering is handled entirely by GTK. The application is first and foremost a GTK font manager and is intended to be WYSIWYG in terms of font rendering with regards to GTK applications. We disable font fallback because a font manager should not simply substitute characters from a different font in previews, obviously, but we don't force anything, what gets rendered is up to the GTK stack.

I agree with you. So that's the default behavior of GTK. I didn't knew (I'm mostly a Qt user). I thought File Manager was overriding GTK behavior on this point (but yes I just checked with Gimp and Gedit to see they behave like this, you're right).

So what about non-GTK apps (Qt, WxWidgets, Tk, Motif, GNUsteps, FLTK, Athena, raw X apps, etc.)? That's another reason why I think if File Manager display the GTK behavior by default is ok but having an option to display the fallback would be useful.

**Comment by JerryCasiano** [comment]
Because it will be the glyph use in real life applications such a Libre Office, VTE (terminals), file explorers, virtually any app on the system. 

No, it won't. 

GTK applications will not display that glyph.  And how fonts render in GTK applications is really all we're actually concerned about. Especially in regards to a glyph that you are unlikely to see anyway.

If other toolkits or application which do their own rendering decide to do it differently, oh well.

And again, why would we do extra work to show you something that's possibly broken, i.e. a blank, when we already show you something that's clear, consistent and conveys the same information? That's nonsense.

In any case, you'll need to file this request higher up the stack, probably Pango. 

It's not something I'll be putting any effort into.
