### ISSUE TITLE
features requests for character map mode

### ISSUE THREAD

**Issue by teto** [FontManager/font-manager#30]
First of all, let me say I have installed a few font manager programs but this is the best.

I just wanted to suggest two minor improvements in "character map" mode:
- add ability to search for a specific character and jump to it (via unicode number or via character itself ?).
- when displaying all characters, alternate colors for each "block" ('latin-A', 'latin-A supplement').

The reason why I started a font manager in the first place is to debug a fontconfig problem. I wonder if it would be possible to ease the debug process via for instance, showing the different fonts used to print a string etc ?

**Comment by JerryCasiano** [comment]
The character map definitely needs work, agreed.

Currently font manager uses the gucharmap library since it provides, well, everything you see as far as the character map goes. But, unfortunately it doesn't have much in terms of flexibility and doesn't allow for a lot of things that make sense in a font manager or that would just be nice to have.
It is the quickest/easiest way to have a character map integrated in the application though.

It will definitely be reworked, but getting a character map right isn't easy or quick, so it's really something that I don't expect to have until we're closer to a 1.0 release. :-(

Searching for specific characters in various ways is definitely a must. The colors thing, I like a lot I'll have to keep that in mind. Thanks.


As far as debugging font issues, not really sure what you mean? Maybe you could clarify that.
If run from the command line the application has a verbose flag that does output a lot of information, most of it probably useless unless you're me. For now it's mostly concerned with helping debug the application itself but in the future I would rather it only output info useful to the user.

Thanks for the feedback!

**Comment by teto** [comment]
I am glad you are positive about the proposed features :)

Let me explain my usecase - a common one IMO:
I had my terminal displaying multicell characters, which spill on neighbor characters (incriminated character http://www.fileformat.info/info/unicode/char/26a0/index.htm):
![2017-02-22-134647_251x344_scrot](https://cloud.githubusercontent.com/assets/886074/23238083/9966f234-f960-11e6-80e7-a1b3544a3c7b.png)
While I now understand the problem (terminal using a monospace font but falls back on FreeSerif to display a missing character from the current font), it was not clear at the time as I knew little about fonts and such. I wish there was a program that would accept a string as input and then show for each character which was the font used. Right now, I rely on https://repolinux.wordpress.com/2013/03/10/find-out-fallback-font-used-by-fontconfig-for-a-certain-character/

**Comment by JerryCasiano** [comment]
I see. That's actually not difficult and I can see it being useful. 

Currently I disable fallback everywhere since you don't want a font manager displaying characters that aren't actually in the font. But we'll have to work that in somewhere, like a debug window/feature or something. Features like this are more about presentation than the actual implementation, let me think about this. ;-)

**Comment by JerryCasiano** [comment]
The first part of this request is implemented in master.

The character map search bar allows searching by character, codepoint or name.

Unfortunately it's been quite a while and there have been many changes since this request so the second part, while I really liked the idea, no longer applies to the current design. 

I'll leave this open a little longer in case anyone has any feedback on the new search feature.

**Comment by JerryCasiano** [comment]
@teto 

So, as far determining fallback fonts...

I've been thinking about where this type of feature would fit in within the application and I'm not really coming up with anything. If you have any input on where and how it would be presented I'm all ears. Otherwise I think this is just "out of scope".

However, I did do some prototyping so I'll attach the result here in case it is useful.

[id_fallbacks.py.txt](https://github.com/FontManager/font-manager/files/3204927/id_fallbacks.py.txt)

To try it out remove the .txt, github won't attach certain filetypes, and either make it executable and run it directly or 

    python id_fallbacks.py

You can select a font then type a string and the list will show you characters and the font used to render them with any fallbacks at the top.

**Comment by JerryCasiano** [comment]
Anyway, closing this out for now but feel free to continue any discussion regarding the features that didn't make it in here.

Thanks!

**Comment by teto** [comment]
thanks for the follow up.
