### ISSUE TITLE
font-manager generate 39-Aliases.conf with empty prefer

### ISSUE THREAD

**Issue by iyzsong** [FontManager/font-manager#306]
font-manager 首選項中的替換功能未生效，雖然提示保存成功，但生成的 39-Aliases.conf 文件中 `prefer` 爲空。

界面提示:
![截图_2023-01-27_16-46-55](https://user-images.githubusercontent.com/22543694/215046204-01d841ad-d60a-4486-a412-7810b3e07225.png)

39-Aliases.conf 文件:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by Font Manager. Do NOT edit this file. -->
<fontconfig>
  <alias binding="strong">
    <family>Arial</family>
    <prefer/>
    <accept/>
    <default/>
  </alias>
</fontconfig>
```

終端輸出:
```
[font-manager]-Message: 16:44:18.778: ArchiveManager.vala:59: Install file-roller to enable archive support
Fontconfig error: No writable cache directories
(font-manager:23601): [font-manager]-WARNING **: 16:44:19.423: GoogleFonts.vala:185: Failed to download data for : gfc-alpha.json :: 2
(font-manager:23601): [font-manager]-WARNING **: 16:44:43.897: Requested invalid member : 喜好
(font-manager:23601): [font-manager]-CRITICAL **: 16:44:43.897: file ../font-manager-0.8.8/lib/common/font-manager-alias.c: line 230 (font_manager_alias_element_get): should not be reached
(font-manager:23601): [font-manager]-CRITICAL **: 16:44:43.897: font_manager_string_set_add: assertion 'self != NULL' failed
```

系統: ArchLinux
版本: font-manager 0.8.8-1

**Comment by JerryCasiano** [comment]
Looks like we might be using the translated text in the wrong place. 

I'll try to have a look over the weekend.

Thanks for reporting.

**Comment by clover-yan** [comment]
@JerryCasiano @PF4Public

Hello, I met the same issue. I'm using Ver `0.8.8` on Ubuntu 22.04 LTS, this issue still remains. My location is `zh_CN`. 

When I set the alias and save, the configuration never remains and I loss my config after restarting the app. I tried to edit the `39-Aliases.conf` file manually, and when I reopen the app, it shows `prefer` instead of localised context (`喜好`). **I think it's because the `prefer` `accept` `normal` texts should not be translated.**

*Here's an image example. Texts are manually modified in the GUI, just to show how the issue takes place.*
![image](https://github.com/FontManager/font-manager/assets/56215525/fba60f30-5ba8-4ae2-a09e-12626e510716)

**Comment by clover-yan** [comment]
I think it is better to reopen this issue to make the problem well-tracked.

**Comment by clover-yan** [comment]
I searched on Hosted Weblate. I think once we set the three strings below to the original English words, the issue will be fixed.

- Set to [prefer](https://hosted.weblate.org/translate/font-manager/font-manager/zh_Hans/?checksum=c8a59a2811ef4e5f&sort_by=-priority,position).
- Set to [accept](https://hosted.weblate.org/translate/font-manager/font-manager/zh_Hans/?checksum=e6f56789bbb979d5&sort_by=-priority,position).
- Set to [default](https://hosted.weblate.org/translate/font-manager/font-manager/zh_Hans/?checksum=25345498e7a25d64&sort_by=-priority,position).
