### ISSUE TITLE
webkit2gtk-4.0 version outdated

### ISSUE THREAD

**Issue by Eonfge** [FontManager/font-manager#317]
**Describe the bug**
webkit2gtk-4.1 is compatible with webkit2gtk-4.0, the difference is that it links with libsoup3 instead of libsoup2. As such, Font Manager can't be compiled against the Flathub GNOME 43 runtime.

**To Reproduce**
Steps to reproduce the behaviour:
- https://github.com/flathub/org.gnome.FontManager/pull/18

**Additional context**
 I ran into this problem before with another project:
https://github.com/flathub/com.github.fabiocolacio.marker/pull/34

There are two options;
- I can make a small patch for Flathub only,
- You make a small change and publish a new release

The second option is of course preferred, but if that's not possible I'll go for option one.

**Comment by JerryCasiano** [comment]
Hmm.

I think for now I would appreciate it if you patched it.

I'm really trying to hold another release off for as long as possible this time around as I would prefer to tag the GTK 4 port as 0.9

So if you can patch and build please do that for now and we'll keep this issue open till it's fixed in the next release.

**Comment by PF4Public** [comment]
@JerryCasiano Do you plan full GTK 4 support for 0.9 and deprecating GTK 3 by that time?

**Comment by JerryCasiano** [comment]
@PF4Public 

I'm hoping the GTK 4 port will be ready in the next 6- 12 months while at a minimum matching the current feature set. 

If that does happen, then yes, it'll release as 0.9 and basically replace the current version.

I don't think that we can support both at the same time though I haven't gotten to the point where that's even something to look into.

Why do you ask? Are you hoping the GTK 3 version sticks around longer?

**Comment by PF4Public** [comment]
> Why do you ask?

Upgrading to GTK 4 is definitely not a simple version bump and might require some attention from me (in the sense of packaging for Gentoo), just asking to be prepared :)

>Are you hoping the GTK 3 version sticks around longer?

Honestly saying that doesn't matter much, provided that no functionality is lost :) And of course it would be easier to support just one variant, especially since GTK 4 is advancing rapidly. I did ask if compatibility is possible before, but now it is obvious that GTK 4 is the way to go.

**Comment by JerryCasiano** [comment]
The latest commit closes this issue.

I apologize for the time lapse between this request and its resolution, really not good.

Unfortunately GTK 4 had been... let's say discouraging work on the project. 

Well that and life but yeah.

I'm going to try get back into this and get the port finally completed.

Just in time for GTK 5 probably. 😁

**Comment by Eonfge** [comment]
No problem. The past year I've spend a lot of my time on 'life' as well. From moving in with my love, up to legal disputes with my landlord.

Sometimes, things just take some extra time. In hindsight, seeing how poorly Flatpak supports Font Manager's features... I wished I didn't make the package in the first place.
