### ISSUE TITLE
font-manager hangs on start

### ISSUE THREAD

**Issue by abma** [FontManager/font-manager#318]
when starting font-manager 0.8.8-2 on debian 12 it just hangs.

```
$ netstat -tanp |grep font-manager
tcp        0      1 <localip>:49496    142.251.209.138:443     SYN_SENT    694812/font-manager 

```

my firewall blocks access to the internet, only via a proxy server is possible.

why does font-manager try to connect to the internet at all / how can i disable this?

after like 5 minutes a error message is shown in console:
`
(font-manager:694812): [font-manager]-WARNING **: 16:35:27.251: GoogleFonts.vala:185: Failed to download data for : gfc-alpha.json :: 4
`

**Comment by PF4Public** [comment]
Well, lets see what @JerryCasiano has to say.

**Comment by JerryCasiano** [comment]
If you could please build from master and verify that the application correctly detects network status without hanging on your setup that would be appreciated.

As far as disabling the application from even trying to access the network at all, compile the application without support for WebKit, there's a flag for that.

Sorry but I'm not really inclined to add a setting for this since we already provide a way to completely eliminate that feature.

**Comment by PF4Public** [comment]
>from privacy point the change makes it just worse as now two servers are connected.

Agreed! This was one of the reasoning for making it optional at the first place: #137

>send personal data to strangers which font-manager does when it starts

Which personal data are sent by font-manager? Nothing identifying — for sure!

>debian won't change the compile flags as there are reason to keep it enabled

IIRC Debian allows recompiling from sources and installing modified package inplace.

**Comment by PF4Public** [comment]
> an IP-address is by definition personal data: as it allows to identify an individual.

Well, if you insist on definitions.

> Natural persons may be associated with online identifiers provided by their devices, applications, tools and protocols, such as internet protocol addresses, cookie identifiers or other identifiers such as radio frequency identification tags. This may leave traces […]

By definition IP address _may_, not _must_ act as online identifier. Since you've mentioned that you're system administrator, I assume you're aware that locally administered IPv4 address does not leave your network in HTTP requests (unless you allow your proxy to do so). So from outside of your network, you use another IPv4 address(es), which alone cannot possibly act as online identifier(s). Of course it gets interesting with IPv6.


Nonetheless, you have the ability to build font-manager from source and disable google fonts integration. No issues with that.

**Comment by JerryCasiano** [comment]
> please stop trolling me.

Nobody is trolling you.

@PF4Public is just stating facts and giving you the only advice that is actually useful at this point in time.

If your situation is that the current version of the application violates laws in your country then your only viable option at this point in time is to recompile the application with the functionally disabled and deploy that to your users or modify your firewall configuration.

Yes, we can change the application to lazy load Google Fonts only when requested and yes we can provide a setting which prevents the application from connecting, we could even pop up a dialog informing the user before proceeding BUT none of that is going to happen anytime soon and may not happen at all for the GTK 3 version.

> i hopefully you agree that a (runtime) config setting is a better solution.

I'm not sure I do...

What's wrong with adding a rule to reject requests from the application? Or modifying desktop files for your users?

How would adding a runtime setting resolve your situation anyway? You would still have to modify something, right? Otherwise you have the exact same issue on first run.

**Comment by JerryCasiano** [comment]
@abma 

Ok  We'll add a setting for the next release.

When that will happen. No idea.

**Comment by JerryCasiano** [comment]
@abma 

Actually, I have more questions for you 

In your scenario, is the user allowed to change that setting? If they are and they do, they run into the hanging problem correct?

So maybe we need a message explaining to the user that network access is restricted by the administrator?

I think we have two choices. We don't expose the setting in the interface at all and we don't inform the user why the application can't access the network.

We expose the setting but only allow changing it based on the value of another hidden setting and we explain to the user why they can't access the network.

However, that still doesn't address the actual legal issues in your country. So, it appears we need a third setting to inform and request permission before accessing the network?

Trying to understand the best way to address this situation long term 

Thanks.

**Comment by JerryCasiano** [comment]
The requested change is now in master so I'm closing this out. That said, we are not planning any releases anytime soon.

Development focus is on the GTK 4 version which is still a ways out, 0.8.9 will be the last release for GTK 3 so putting it off for as long as possible at this time.

**Comment by oldherl** [comment]
I'm experiencing this too, on Arch Linux. I live in China, where Google Fonts is not accessible. Is there an option somewhere that turns off Google Fonts?

**Comment by bbbbbr** [comment]
> I'm experiencing this too, on Arch Linux. I live in China, where Google Fonts is not accessible. Is there an option somewhere that turns off Google Fonts?

If I understand the discussion above right, it looks like running the command below might turn off the network access attempt. Maybe requires version `0.8.9` or higher, but not sure since I didn't see an entry in the changelog or release notes and I haven't dug too deep into the commit history and tags.

`dconf write /org/gnome/font-manager/restrict-network-access true`

Came here for a similar reason as some other people posting in this issue btw.
