### ISSUE TITLE
Cyrillic orthography is named in russian

### ISSUE THREAD

**Issue by iRomanyshyn** [FontManager/font-manager#336]
Basic Cyrillic and Full Cyrillic orthography are named in russian even in my English localized system. It is not OK because [Cyrillic orthography](https://en.wikipedia.org/wiki/Cyrillic_script) is used across tens of languages and those languages are separate from russian or even russian is a child of those languages.

![image](https://github.com/FontManager/font-manager/assets/11888301/4d8c6b80-aee1-41bd-8afa-6024be3d6c2f)

**Comment by JerryCasiano** [comment]
I'm closing this as invalid for two reasons.

1. I believe the estimate is that Russia accounts for around half of the users in the world, so I'm not sure this is a valid complaint.
2. Even if your complaint is valid you have not provided any input on how to correct the issue, at all.

Feel free to reopen this once you are ready to propose a solution and explain the rationale behind it.

**Comment by skurzinz** [comment]
I think this is about the translation of "Basic Cyrillic" into "кириллица" in the label, which is Russian (double лл). Cf. info box at https://en.wikipedia.org/wiki/Cyrillic_script for other names. 

A point against changing anything would be that also e.g. "Basic Latin" is English, even though that same label could be spelled in many other languages that use the Latin script. So this is merely a localization issue. If those labels were translatable, "Basic Latin" could be German "Grundlegende lateinische Schrift" and Serbian "Basic Cyrillic" could be "Азбука" or "ћирилица".

**Comment by JerryCasiano** [comment]
@skurzinz 

Interesting point.

There's two labels used there the top one is the "name" and the bottom larger one is the "native name".

I believe the "name" label is already marked for translation. I guess we could also mark the "native name" for translation, that's pretty easy. 

But since the OP posted a picture from a system set to English it would make zero difference there.

**Comment by skurzinz** [comment]
@JerryCasiano marking the "native name" label for translation would enable to localize it. Most scripts have a widely accepted native name anyway, but where there's a one-to-many relation between name and native name that would make sense. 

Using a German language interface I saw a few strange English fallback strings, so I went through the German translation on weblate.

**Comment by JerryCasiano** [comment]
Actually it probably wouldn't work very well since translators are unlikely to understand such a wide variety of languages. It would likely just make all translations incomplete and I think this is why they aren't marked.

What we could do, I guess, is use the name label for both if a translation exists for name.

But that means doing string comparisons over and over so I'm just not completely convinced it's even worth bothering. But it's pretty easy to do so something to consider for the next version.

**Comment by skurzinz** [comment]
I suppose this affects quite some major script systems such as Latin, Arabopersian, Devanagari et al. which are each used for a host of languages or spelling variants in denoting the script system. But the fact that no one complained about this so long points toward a) it's not worth bothering and/or b) Font manager is underused in affected areas of the world.

@iRomanyshyn What would be the preferred label that is (pan-slavically?) universally understood to cover the glyph range of "Basic Cyrillic" (cf. https://en.wikipedia.org/wiki/Cyrillic_script_in_Unicode)? "Cyrillic" (in any localized form) may be unspecific anyway. Would reverting back to the name label (literally "Basic Cyrillic") work in this case?
