### ISSUE TITLE
Add support for "embolden" option

### ISSUE THREAD

**Issue by MarjaE2** [FontManager/font-manager#340]
**Is your feature request related to a problem? Please describe.**

I have trouble reading thin or faint text. Increasing font sizes to 30 to 40 pts isn't practical, and still leaves them awfully thin. I have been using bolder fonts such as Roboto Slab, but not all scripts have these.

**Describe the solution you'd like**

I read that older versions of fontconfig had an "embolden" option. If I open my "fontconfig" files, I get a warning not to manually edit them. If fontconfig still has an "embolden" option, then font-manager should include a setting to enable this.

**Describe alternatives you've considered**
Manually editing fontconfig. Uninstalling font manager and manually editing fontconfig.

I fear screwing things up.

Trying to find bolder fonts.

But if I'm writing the same document on different systems, I want it to be clear in each system.

If there's a way to create good synthetic semibolds, bolds, italics, etc. and share these between systems so each app can use them, that would also help and might also work around this.

**Comment by JerryCasiano** [comment]
I think there may be a misunderstanding or two here.

The options the application exposes are global and not pattern specific.

As far as I understand it the embolden option within Fontconfig is pattern specific and all it actually does is synthetically generate a bold variant for a font or family which doesn't have one. So even if we did expose that option and apply it globally to all patterns, which would be completely inappropriate, it wouldn't give you the result you're after, it would not make all fonts bolder.

In any case, feel free to experiment and find out.

You do NOT need to edit files generated by the application in order to modify the Fontconfig configuration.

Any valid configuration file found in ~/.config/fontconfig/conf.d should be read and honored. Ensure that you use a valid filename and a high enough prefix that your file is read last i.e. 99-personal.conf

Undoing any changes is as simple as deleting any added files or even the entire folder if you want to start over. So no need to be afraid, as long as you have another account on the system and admin privileges you can always recover no matter how bad the screw up is. 

As far as configuration on different systems go that is completely out of scope. This will of course depend on what filetype you are using. Some formats allow specifying fonts and are probably what you want to use while selecting a common bold font that is both readable to you and likely to exist on most systems.

Hope this helps.

I'm closing this as invalid but feel free to ask any other questions here or clarify anything if I misunderstood in any way. Sorry but I just don't think this is something that the application can actually help you with. I really do think this is something that needs to be addressed by the OS accessibility settings or by editor settings.
