### ISSUE TITLE
Cannot navigate categories with arrow keys

### ISSUE THREAD

**Issue by WhyNotHugo** [FontManager/font-manager#349]
**Describe the bug**

I can't navigate the categories tree on the left with the arrow keys.

**To Reproduce**
1. Click on the categories tree somewhere
3. Press up or down

**Actual behaviour**

Nothing happens

**Expected behavior**

The selected category should move up or down

**Screenshots**

n/a

**System Information**
 - OS: Alpine Linux Edge
 - Desktop Environment: swaywm
 - Font Manager version: font-manager-0.8.8-r6 
 - Font Manager installation method: distribution package

**Additional context**

Additionally, focusing some other element and pressing <kbd>tab</kbd> or <kbd>shift</kbd>+<kbd>tab</kbd> does not allow focusing the categories tree.

**Comment by JerryCasiano** [comment]
Keyboard navigation appears to be working as you expect it to in the GTK 4 work in progress branch.

So, the good news is that your issue will be fixed when that releases. With the bad news being that it's still going to be a little while...

Thanks for reporting this though and sorry that it won't get fixed in the current version.
