### ISSUE TITLE
Allow browsing through fonts with custom text

### ISSUE THREAD

**Issue by bradrn** [FontManager/font-manager#378]
**Is your feature request related to a problem? Please describe.**

Often I want to compare some text across a wide range of fonts — for instance, to compare something across many different typefaces, or to test font coverage for a set of characters. This is impossible to do in current Font Manager. Before the GTK4 update, it was possible (albeit annoying) to specify some text in ‘Browse’ mode and page through the fonts shown there, but it seems that this is now impossible. Custom text can still be specified in ‘Compare’ mode, but only for a pre-selected set of fonts.

**Describe the solution you'd like**

The ability to specify custom text in the ‘Browse’ tab, to be displayed in place of the font name.

**Describe alternatives you've considered**

To be completely honest, I can’t really think of any. This seems like a fairly basic feature for a font manager to have. But I’m open to any ideas other people may have!

**Additional context**

None.

**Comment by JerryCasiano** [comment]
So, two things. 

One is that you can start a search with a colon to filter based on character support. 

And the other is that I need to know what " (albeit annoying) " actually means.

Otherwise it'll be implement the same way, actually it's already implemented the same way... 

The reason it wasn't included in the initial release is that it's now affected by performance issues and a bug I find very annoying. 

See https://gitlab.gnome.org/GNOME/gtk/-/issues/4717 and https://gitlab.gnome.org/GNOME/gtk/-/issues/4751 for more details.

It doesn't look like that bug is ever getting fixed though so we probably will end up shipping the list view as-is in the next release.

If you have any ideas, mockups, examples, etc. now is the time to share, otherwise it's pretty much the same thing as before but a little slower and with janky scrolling.

**Comment by skurzinz** [comment]
Not really FontManager related answer but it might help @bradrn anyway: Web based solution for the question "does my font include char X" and "does my font have all glyphs I need for language Y": https://hyperglot.rosettatype.com/. 

Their glyph lists per language ("orthographies") are seemingly also under GPL-3.

**Comment by bradrn** [comment]
> One is that you can start a search with a colon to filter based on character support.

Oh… very interesting, thanks! Not a complete solution, but helpful nonetheless.

(Are there any other shortcuts like this? I can’t see the colon documented anywhere.)

> And the other is that I need to know what " (albeit annoying) " actually means.

The UI used to be a bit clunky, that’s all. In particular, I remember that it was difficult to fit all the fonts on the screen, and pagination in ‘Browse’ view was annoying. But it looks like the GTK4 redesign has already fixed these issues: all that is missing is the ability to specify text other than the font name.

> If you have any ideas, mockups, examples, etc. now is the time to share, otherwise it's pretty much the same thing as before but a little slower and with janky scrolling.

OK, here’s an attempt at a mockup:

![font-manager-mockup](https://github.com/FontManager/font-manager/assets/17613703/8e9b36c2-ee76-498f-b2e4-95b3dbb6cfb6)

I don’t have the time to go through the image and replace _every single box_ with the custom text, but hopefully this should show the principle.

**Comment by JerryCasiano** [comment]
@bradrn 

> (Are there any other shortcuts like this? I can’t see the colon documented anywhere.)

Just one other at this time. If you hover over the search field for a second you should get a tooltip which shows both of them..

Starting a search with / will filter by filepath, just a portion of the path is fine.

Those are just workarounds, eventually we'll get a more advanced search but it's low priority.

> I don’t have the time to go through the image and replace every single box with the custom text, but hopefully this should show the principle.

Completely understand. That's pretty close to what's already implemented so we should be good then. The only difference is the entry is at the bottom since it's close to the toggle for it.

I'll leave this open for now, we'll ship this in the next point release. If you're using the COPR or PPA packages you'll likely get it sooner - still seeing if we can improve a couple things before merging it.

**Comment by bradrn** [comment]
> That's pretty close to what's already implemented so we should be good then […] we'll ship this in the next point release.

Oh, excellent, thanks very much!

**Comment by JerryCasiano** [comment]
@skurzinz 

That's really interesting. Thanks for sharing!

Will probably look into using their database instead, it looks like it would be mostly compatible with how we use the Fontaine data anyway and Fontaine is no longer active.

**Comment by JerryCasiano** [comment]
Changes are now in master and If you are using the COPR or PPA packages you should see those update within a day or two at most.

Otherwise you can build from source or wait for 0.9.1 which will likely release next month.

Thanks

**Comment by bradrn** [comment]
I just tried out master, and it works great, thanks!
