### ISSUE TITLE
Preview text disappeared

### ISSUE THREAD

**Issue by Moilleadoir** [FontManager/font-manager#385]
**Describe the bug**
I often use Font Manager to tell how well a font supports particular characters (e.g. IPA, particular used in representing Irish/Old Irish, dotted letters ḃċḋḟġṁṗṡṫ⁊, Gothic letter forms, Indic, etc.), so I had, over years, compiled a preview text covering different languages/scripts.  I’m guessing the program has been updated recently as the preview text is now just back to the default couple of lines.

**To Reproduce**
There aren’t really steps.  It just isn’t there.

**Expected behavior**
The previous preview text should have been kept.
I can’t see any sign of it in `$HOME/.config/font-manager`, but I don’t think I’ve ever looked for the config files before, so maybe they weren’t there.

**System Information**
 - OS: Manjaro
 - Desktop Environment: Cinnamon
 - Font Manager version: 0.9.0-1 
 - Font Manager installation method: Official Resositories (extra)

**Comment by JerryCasiano** [comment]
Those settings are stored in dconf

The current release uses a different identifier and previous settings did not carry over.

You can use something like dconf-editor or use dconf directly to retrieve your previous preview string from the old settings.

Closing this as it's not an actual bug. We probably should have migrated some settings but what's done is done.

I'm not near a computer otherwise I'd give you the command to retrieve the previous setting.

I'm closing this but of you have any other questions feel free to ask here. Thanks.

Also, the next point release will restore the preview text entries in browse mode, just FYI.
