### ISSUE TITLE
Useful features from version 0.5.x

### ISSUE THREAD

**Issue by kitaets** [FontManager/font-manager#48]
There are several useful features in version 0.5.x, which I used, but haven't found in version 0.7.3:
- Saving all fonts from a collection (via archiving or coping);
- Finding out a font filename and it's placement (folder);
- User actions for fonts (less needed feature).

Is it future requests or it's possible at the moment?

**Comment by JerryCasiano** [comment]
These features will definitely be added back at some point.

Sorry I can't be more specific than that right now but there's a lot of breaking changes going on "under the hood" at this point so I'm not really planning on doing anything till that's sorted out.

Exporting collections is also important to me, but it'll have to wait till we switch to using libarchive directly.

**Comment by JerryCasiano** [comment]
@Sadi58

Sorry. Started doing some refactoring a while ago and it's taking much longer than expected due to time constraints, lack of motivation, etc.

Which is typical. :-/

But, I'm hoping that even at the pace that it's going it should only be a few months before you see something.

I'll add a testing branch as soon as it's useable and actually builds again. 

The feature you're looking for and several others will definitely be resolved in the next release which will happen some time this year.

Though exporting collections may or may not make it in.

Thanks for your interest.

**Comment by JerryCasiano** [comment]
[testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

Right clicking in the font list will allow copying the file path or show in folder.
Other features still in progress.

**Comment by JerryCasiano** [comment]
Most of this issue is resolved in the testing branch at this point.

Right clicking in the collection list should give you the option to copy, and compress if you have file-roller installed, the selected collection.

User actions haven't been implemented yet, not sure when that will happen.

**Comment by Sadi58** [comment]
Thanks a lot for adding "**Copy Location**" and "**Show in Folder**" options to context menu - very very usefull in deed!
