### ISSUE TITLE
[enhancement] Integrate Typecatcher's function

### ISSUE THREAD

**Issue by hThoreau** [FontManager/font-manager#54]
Hello there,

I'm seeking to reduce the amount of installed programs by applying the "law of othogonality". That is, to quote the [fish shell](https://fishshell.com/docs/current/design.html) design document "Any situation where two features are related but not identical, one of them should be removed, and the other should be made powerful and general enough to handle all common use cases of either feature."

So, on that regard, [Typecatcher](https://github.com/andrewsomething/typecatcher) in relation to Font Manager, similarly functions as a (lesser) font manager, though cabable of navigating the Google Fonts Catalog. So, if Font Manager could be able to draw fonts from that repository or, even better, from [Font Squirrel](https://www.fontsquirrel.com/), well, that would make, for me at least, having Font Manager the sole tool necessary to perform all tasks related to font management.

Thanks,

**Comment by JerryCasiano** [comment]
Completely agree. Matter of fact it's something that I wanted/planned to do.

However, there are just so many basics that aren't there yet that this is very low priority.

It will eventually happen, I hope, probably in the form of plugins for each online source. 

Thanks for your interest.

**Comment by pathumego** [comment]
You might be interested in this. Open to collab https://github.com/fontpackage

**Comment by JerryCasiano** [comment]
For anyone interested in testing and providing feedback there is now a work in progress branch.

Please build from the [google-fonts-integration](https://github.com/FontManager/font-manager/tree/google-fonts-integration) branch and report any errors encountered.

**Comment by JerryCasiano** [comment]
Closing this out as the changes are now in master and will be part of 0.8 which should be released soon.

**Comment by JerryCasiano** [comment]
As far as [Font Squirrel](https://www.fontsquirrel.com/) goes I wasn't able to find any kind of API and with a mix of free / paid fonts which in many cases link to third party sites it looks like it would be a real pain in the ass to support.

I'm happy to look into adding other providers so long as they provide a proper and stable API.

**Comment by pathumego** [comment]
@JerryCasiano Please look at https://type.world/ and https://github.com/typeworld/typeworld. It is still not in mass use, but hopefully will pickup in the coming years.

**Comment by JerryCasiano** [comment]
@pathumego 

I ran across a forum discussion regarding that project a little while ago.

Doesn't look like much has changed since then.

If and when the API portion starts getting adoption, it may be worth looking into supporting.

But honestly, I don't have high hopes, for various reasons.

Anyway, thanks for sharing.

**Comment by PF4Public** [comment]
Could it be possible to make external (network) integrations optional? I assume, that's why libsoup is now in dependencies…

**Comment by JerryCasiano** [comment]
@PF4Public 

So... I've hesitated to implement this feature for this long because I didn't want to have a hard dependency on these libraries.

Unfortunately my attempts to make it optional failed, issues with meson / vala.

Though I'll admit I gave up pretty easily on this. So, I'll probably revisit it and try to figure out a way to make it optional.

Feel free to file an issue for this, I don't like it being a hard requirement either, you should be able to opt out.
