### ISSUE TITLE
Conflict with gnome extension clock_override

### ISSUE THREAD

**Issue by farzadmf** [FontManager/font-manager#69]
Hi,

I have installed this package on Ubuntu 18.10, and I'm using the gnome extension [clock_override](https://github.com/stuartlangridge/gnome-shell-clock-override). They have a cool thing that you can configure your clock to show a bell icon, but I noticed that if I enable the `Antialias` setting in `font-manager`, it causes that bell icon to appear as blank.

I really like the smoothness I see with the anti-alias option, but it would be great to have the best of both worlds :)

In case you may need more information, here's the issue I opened in that repo:
stuartlangridge/gnome-shell-clock-override#35

**Comment by JerryCasiano** [comment]
This is not what I would call a conflict.

It's certainly not an application bug. 
The application is simply generating the fontconfig configuration you asked it to. 

Without knowing anything about your installation and just going off of the screenshot you posted in the linked issue the only thing I can tell you is that on *most* systems anti-aliasing is enabled by default, meaning that on *most* systems all you would actually accomplish with those settings is to disable hinting and embedded bitmaps, which are typically also enabled by default on *most* systems.

Any side effects that may have on whatever font you've decided to use is not something that we can "fix" aside from just removing those settings altogether so that you can't change them.

I'm sorry, but I'm not really understanding what you would like done about this?

For reference, these are the default settings on most mainstream Linux distributions.

![default_fontconfig_settings](https://user-images.githubusercontent.com/11490124/51508060-c1deab80-1dc1-11e9-8c5e-436016ec6b23.png)

**Comment by JerryCasiano** [comment]
Oh good. Glad to hear that.

**Comment by JerryCasiano** [comment]
> I'm on Ubuntu 18.10, and I don't know if it's because of other things I installed or by default, by when I go to the settings page of font-manager, all the settings in the Rendering section were turned off.

Sorry, this is resolved in the latest version.

Previous versions didn't query current settings but latest release will query current settings and show that instead of being blank.

Hopefully Ubuntu updates soon.

**Comment by farzadmf** [comment]
I'm not sure if I understand you correctly, but I *think* (I'm not sure) that the settings being displayed in `font-manager` were reflecting "reality" because I could definitively see the difference when I enabled the "Antialias" option in `font-manager` (meaning that it *was* off)

**Comment by JerryCasiano** [comment]
No, those didn't actually reflect the current configuration till the changes from 0.7.4 were merged, they just allowed generating a configuration if you wanted to.

0.7.4 shows the configuration used by the default system font which should be accurate unless the user has customizations.

0.7.5 will probably allow per font settings, not sure about this yet.

**Comment by farzadmf** [comment]
Thank you @JerryCasiano anyway for this package. I'm really enjoying the smooth font I'm seeing now. Just maybe I can ask another question: when I open a font and select install with this application, where does it put the font?

Thank you

**Comment by JerryCasiano** [comment]
Of course, I'm happy to answer any questions I can.

It organizes your fonts in the default user font directory which at this time is `$XDG_DATA_DIR/fonts`

`$XDG_DATA_DIR` defaults to `~/.local/share` so unless you've changed it you should find any installed fonts in `~/.local/share/fonts`

They'll be organized by Vendor -> Filetype -> Family

HTH

**Comment by farzadmf** [comment]
Thank you for your answer. I'm not sure if it's again something I've done, but on my Ubuntu 18.10, the `$XDG_DATA_DIR` variable is empty, and the only similar variable I have is `$XDG_DATA_DIRS`.

Also, as an example, I downloaded and opened `Consolas` with `font-manager` and then selected `Install Font`, but when I go to `~/.local/share/fonts`, I don't see it there

**Comment by JerryCasiano** [comment]
I'm sorry that should have been `$XDG_DATA_HOME` and that is definitely where they are stored.

I'll double check on my Ubuntu install when I get home and let you know.

**Comment by JerryCasiano** [comment]
The attached screenshot is from a stock Ubuntu 18.10 install. 

You should be seeing something similar unless something is way off about your setup.

![screenshot from 2019-01-22 22-11-36](https://user-images.githubusercontent.com/11490124/51580496-b4452680-1e92-11e9-88cb-796ab549551c.png)

**Comment by farzadmf** [comment]
Thank you @JerryCasiano , I REALLY appreciate you taking the time to do all this.

And yes, you're right again ;) . When I did a listing of my `~/.local/share/fonts`, I thought all the fonts would be in this directory; I didn't know that there would be directories in there.

And so, yeah, I checked inside of those directories, and things seem to be in place! :)

Thank you again for all the help

**Comment by JerryCasiano** [comment]
Your welcome.
