### ISSUE TITLE
[enhancement] Compare - insert into list in family/name  lexical order

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#82]
Whilst adding fonts for comparison I found problems comparing fonts from the same or similar families because they are not listed together. E.g. adding 10 fonts and the 3rd is "Wimp-Out Italic, Italic" and the 10th is "Wimp-Out Expanded, Expanded".

I expected these to be listed adjacent to each other (based on lexical ordering) to make it easier to consider variations from families and find it difficult when comparing large numbers of fonts to compare the subtle variations.

**Comment by JerryCasiano** [comment]
The way fonts are listed depends entirely on how the font files identify themselves.

Fix the metadata so that the family name does not include a redundant style in it and they will display the way you want. 

I agree completely and would like it if font designers stopped doing stuff like this. 

Closing as this is not something that can or should be fixed in the application.
