### ISSUE TITLE
[enhancement] Compare - Allow multi-selection (shift/ctrl) in family list and operations

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#87]
When trying to tick/untick the checkboxes for fonts in the family list it doesn't seem there is a way to select multiple fonts.

It would be nice to have the conventional list-box methods for contiguous or non-contiguous selections:

a) select first font, hold shift, select second font and all entries in the list between them are selected (highlighted)

b) hold down Ctrl key and select multiple fonts to create a dis-contiguous list of selected items

With these multiples selected then allow operations all of them at once:

1. Ticking/unticking any one checkbox would tick/untick all selected items
2. Context-menu operations (Install/Copy/Show) would operate on all selected items

**Comment by JerryCasiano** [comment]
You should use a Collection for this, that is their purpose to allow you to group fonts and operate on them all at once.

Since it's something that can already be easily accomplished I don't see any real benefit in doing this work.

That said, if someone wants to submit a pull request I'll be happy to review. 

Closing until such time.
