### ISSUE TITLE
[enhancement] Compare - support multi-selection and drag-drop from preview pane

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#90]
Having just worked through a list of over 1,000 fonts in the Compare family list and added them to the preview pane, and then edited the preview list down to set of candidates, I expected to be able to select (all) fonts in the preview and make a collection of them.

So far I have found no way to do this short of manually finding each font (again!) in the family list and selecting it. 

Edit: And now I find that deselecting in the Compare Family list pane actually *disables* the font(s) in the system via the font cache! This is so counter-intuitive.

**Comment by JerryCasiano** [comment]
I'm sorry I'm really not understanding what your expectations are.

If you're adding a thousand fonts into the compare list, really you're doing it wrong or at least that is not what the compare pane is intended for. 

The compare pane is intended for comparing a few fonts not thousands. I don't even see how a list that long would be useful to try to "compare" anything since you would be scrolling and scrolling and scrolling.

The behavior of the family list does not change based on mode. It is what it is at all times. If it changed behavior it would probably be confusing. But lets for a moment entertain this idea. What would you expect the behavior of the family list to change to in compare mode?
