### ISSUE TITLE
Missing dependencies ... 0.7.5

### ISSUE THREAD

**Issue by d-j-a-y** [FontManager/font-manager#92]
Hi there, 

Building lasted #0.7.5 i found two missing dep.
* gobject-introspection
* libgirepository1.0 (dev)

---> debian 10

I can fix the readme and pull if you want.
And thank's for your work.

**Comment by JerryCasiano** [comment]
I don't think you need the gobject-introspection package installed but the dev package is definitely a build requirement.

And yes, if you can submit a pull request, please do.

Thanks for pointing it out.

**Comment by d-j-a-y** [comment]
In fact I had a g-ir-scanner (i guess or another gobj-introspection tool..) not found error during build... so i guess both are missing dependencies.

**Comment by JerryCasiano** [comment]
> Any minimum version requirement ?

That is a good question... Not that I know of, so let's not specify any.

Also, I realized after I responded that you are correct the dependency has to be on gobject-introspection as a whole since we can't or at least shouldn't use distribution specific names and not all distributions separate packages anyway.
