### ISSUE TITLE
Did Thunar extension disappear?

### ISSUE THREAD

**Issue by PF4Public** [FontManager/font-manager#94]

**Comment by JerryCasiano** [comment]
Yes. 

See d4fe6a9af4ab458de9db167f846fce9730c9a658

Which dropped all the extensions written in Python.

Nautilus and Nemo extensions were rewritten in C.
Nemo is a fork of Nautilus so the Extension API is identical aside from additions and namespace.

The Thunar extension was also rewritten in C, however, it turns out that it requires deprecated Gtk+ widgets to build, that coupled with the difference in API made the decision to drop it pretty easy.

There's various reasons why it was decided to drop use of Python for the extensions but the main ones are that distributions are starting to drop Python 2 which somewhat complicates packaging and also that I would like to add features to the extensions in the future and dropping then into C is going to make that less of a headache in the long run.

In any case, nothing's stopping anyone from grabbing the old extension from a previous commit and using it if they're happy with it.

Thanks for reminding me I need to update some pages...

**Comment by PF4Public** [comment]
Wow, unexpected! Thanks.
I could miss this, unless I've read the changelog.

@JerryCasiano It would have been great, if you mentioned this here via a message. Github seems not to be sending out notifications on commits :(

**Comment by JerryCasiano** [comment]
I thought about it but assumed it would notify you anyway and didn't want to send a duplicate... Now i know it doesn't. Thanks.

The Thunar API is now close enough to Nautilus and Nemo where it won't be a burden so figured I why not add it back.

**Comment by PF4Public** [comment]
I've just compiled font-manager with thunar extension and can confirm it is working! Awesome!
Thanks again.

**Comment by PF4Public** [comment]
> I thought about it but assumed it would notify you anyway and didn't want to send a duplicate... Now i know it doesn't. Thanks.

Yesterday I clicked watch this repository and thereafter I started receiving e-mail notifications of your every commit, although I have them disabled in preferences. Most interesting is that GitHub does so only with respect to your repository. it doesn't send emails for other repositories, which I'm watching, weird. Just letting you know, not sure if that's a bug or designed so by GitHub. So I switched to watching issues and PRs.

And you were right in that if I've been watching this repository, I should've received an email upon your commit about Thunar :)

**Comment by JerryCasiano** [comment]
Sounds like a bug, since you should be able to control this in your profile email notification settings.

The repository itself doesn't really have any settings as far as that goes and there's no one listed in the notifications pane.

Weird.
